insert into parametres(libelle) values('Emploie');
insert into valeurs(id_param, libelle) values(1, 'Technicien supérieur en informatique');
insert into valeurs(id_param, libelle) values(1, 'Ingénieur des travaux informatiques');
insert into valeurs(id_param, libelle) values(1, 'Adjoint des Cadres Hospitaliers');
insert into valeurs(id_param, libelle) values(1, 'Chauffeur');
insert into valeurs(id_param, libelle) values(1, 'Conservateur d archives');
insert into valeurs(id_param, libelle) values(1, 'Médecin généraliste');
insert into valeurs(id_param, libelle) values(1, 'Agent technique de la statistique');
insert into valeurs(id_param, libelle) values(1, 'Ingénieur de Conception en Informatique');
insert into valeurs(id_param, libelle) values(1, 'Attaché de santé en soins infirmiers et obstétricaux');
insert into valeurs(id_param, libelle) values(1, 'Adjoint des cadres hospitaliers');
insert into valeurs(id_param, libelle) values(1, 'Agent de bureau');
insert into valeurs(id_param, libelle) values(1, 'Gestionnaire des services de santé');
insert into parametres(libelle) values('Catégorie');
insert into valeurs(id_param, libelle) values(2, 'A');
insert into valeurs(id_param, libelle) values(2, 'B');
insert into valeurs(id_param, libelle) values(2, 'C');
insert into valeurs(id_param, libelle) values(2, 'D');
insert into valeurs(id_param, libelle) values(2, 'E');
insert into valeurs(id_param, libelle) values(2, 'P');
